### ISSUE TITLE
Bad interaction between this package and Kadira

### ISSUE THREAD

**Issue by guilhermedecampo** [peerlibrary/meteor-reactive-publish#7] opened 2015-10-29 17:00 UTC
Hey @mitar thanks for maintaining this package. Really cool use `this.autorun` on `Meteor.publish`.

Unfortunately I got an strange error:

```
error caught on publication:  null :  Cannot call method 'idStringify' of undefined
```

I see that you have used the method idStringify [here](https://github.com/peerlibrary/meteor-reactive-publish/blob/707a56eb3e8e63536c00632cfd9d654f8c583681/server.coffee#L111)

I'm using the publication with the `this.autorun` only in a ios-ddp. 
The web app does not use and it shows only when I access it for the first time.

here is the publish:

```
Meteor.publish('time_ios', function () {
  this.autorun((comp) => {
    let isDST = moment().local().isDST();
    let randomId = Random.id();
    if (isDST) {
      let time = Time.findOne({group: 'firstSlotsGroup'});
      time.arrayDateSlots.forEach((dateSlots)=> {
        dateSlots.timeSlots.map((timeSlot)=> {
          timeSlot.time += 3600;
        });
      });
      this.added('time',randomId, time);
      return Time.find({_id: randomId});
    } else {
      return Time.find({});
    }
  });
});
```

As you can see it's a workaround for legacy apps =/
Thanks!

**Comment by mitar** [comment] 2015-10-29 17:43
Which version of Meteor are you using?

**Comment by guilhermedecampo** [comment] 2015-10-29 18:08
`Meteor 1.2.0.2`

**Comment by mitar** [comment] 2015-10-29 18:13
Hm, could you try to make a small reproduction?

**Comment by guilhermedecampo** [comment] 2015-10-29 18:14
I'll try man

**Comment by guilhermedecampo** [comment] 2015-10-29 18:51
@mitar the app is pretty huge and depends on a lots of private packages and connects to iOS app via ddp. 

Pretty hard to make a repro =/

Since it's an error that does not stops the app I'll keep with this until fix this workaround.
Thanks for your time

**Comment by RSchwan** [comment] 2015-11-01 12:35
I use Meteor 1.2.1 and get the same error:

```
20151101-13:32:56.812(1)? Exception from task: TypeError: Cannot call method 'idStringify' of undefined
I20151101-13:32:56.812(1)?     at PublishContext.publish.added (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:259:1)
I20151101-13:32:56.812(1)?     at cursor.observeChanges.added (packages/mongo/collection.js:314:1)
I20151101-13:32:56.812(1)?     at packages/mongo/observe_multiplex.js:208:1
I20151101-13:32:56.812(1)?     at [object Object]._.extend.forEach (packages/id-map/id-map.js:48:1)
I20151101-13:32:56.812(1)?     at [object Object]._.extend._sendAdds (packages/mongo/observe_multiplex.js:200:1)
I20151101-13:32:56.812(1)?     at [object Object].kadira_Multiplexer_sendAdds [as _sendAdds] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:21:1)
I20151101-13:32:56.813(1)?     at packages/mongo/observe_multiplex.js:51:1
I20151101-13:32:56.813(1)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20151101-13:32:56.813(1)?     at Object.task (packages/meteor/dynamics_nodejs.js:123:1)
I20151101-13:32:56.813(1)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
```

**Comment by mitar** [comment] 2015-11-01 18:29
A reproduction please.

Is it maybe because you use Kadira?

**Comment by RSchwan** [comment] 2015-11-01 18:57
Yes maybe

**Comment by mitar** [comment] 2015-11-01 19:00
Is it happening regularly or just occasionally? Can you try running it without Kadira and see what happens?

**Comment by mitar** [comment] 2015-11-02 07:48
In the latest version `packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js` file does not have on line 259 call to `idStringify`. Which version of the package are you using?

**Comment by mitar** [comment] 2015-11-02 08:00
So I cannot help much with a reproduction. Sorry. I am using this a lot in my projects and it works for me.

**Comment by mitar** [comment] 2015-11-02 08:04
So tests are succeeding. But I see now that if I add `meteorhacks:kadira@2.25.0` to test dependencies, I get:

```
Exception from sub recent-posts id pJ22Bxghf7fsXtacm

TypeError: Can't call method on  null
    at TypeError (<anonymous>)
    at module.exports (/Users/mitar/.meteor/packages/ecmascript-runtime/.0.2.6.17qd7jk++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/$.defined.js:3:28)
    at module.exports (/Users/mitar/.meteor/packages/ecmascript-runtime/.0.2.6.17qd7jk++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/$.to-object.js:4:17)
    at Function.keys (/Users/mitar/.meteor/packages/ecmascript-runtime/.0.2.6.17qd7jk++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.object.keys.js:6:18)
    at [object Object].cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:138:1)
    at [object Object].kadira_Cursor_observeChanges [as observeChanges] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:87:1)
    at Function.Mongo.Collection._publishCursor (packages/mongo/collection.js:312:1)
    at [object Object].Cursor._publishCursor (packages/mongo/mongo_driver.js:892:1)
    at publishHandlerResult (packages/peerlibrary_reactive-publish/publish.js:26:1)
    at Computation.<anonymous> (packages/peerlibrary_reactive-publish/server.coffee:158:9)
```

It seems there is some bad interaction between Kadira and this package. @arunoda?

**Comment by mitar** [comment] 2015-11-02 08:05
But it is a different error than what you are getting.

So can you try removing temporarily Kadira from your apps and see if it helps?

**Comment by guilhermedecampo** [comment] 2015-11-02 17:46
Yes @mitar I'll try out remove it =) Thanks

**Comment by arunoda** [comment] 2015-11-02 18:01
@mitar We are so careful not do interfeer with the core Meteor API. Anyway, I'll give a try and see for the issue.

**Comment by guilhermedecampo** [comment] 2015-11-02 20:40
@mitar @arunoda I can confirm that removing Kadira stopped the 

```
error caught on publication:  null :  Cannot call method 'idStringify' of undefined
```

**Comment by mitar** [comment] 2015-11-02 21:13
Yes, but this package monkey-patches publication API quite a bit. So maybe there is some unexpected interference. I was looking at Kadira code but was not sure what exactly is causing it. So which assumption we are breaking.

**Comment by mitar** [comment] 2015-11-02 21:14
BTW, one interesting metric for Kadira might be how many times autoruns are triggered inside open publication. :-)

**Comment by dpatte** [comment] 2015-11-03 18:33
is this an issue with 'this'?

**Comment by mitar** [comment] 2015-11-03 18:38
No, you are using fat arrow in ES6 which should do the same as CoffeeScript binding. So `this` should be correctly outside `this` (thus publish context) inside `autorun` as well. If it would not be, you would not have `this.added` at all.

**Comment by guilhermedecampo** [comment] 2015-11-07 13:28
have a better log here

```
Exception from sub time_ios id 7 TypeError: Object.keys called on non-object
    at Function.keys (native)
    at [object Object].cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:138:1)
    at [object Object].kadira_Cursor_observeChanges [as observeChanges] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:87:1)
    at Function.Mongo.Collection._publishCursor (packages/mongo/collection.js:308:1)
    at [object Object].Cursor._publishCursor (packages/mongo/mongo_driver.js:892:1)
    at publishHandlerResult (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:34:1)
    at Computation.<anonymous> (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:295:1)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    at packages/meteor/dynamics_nodejs.js:121:1
    at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:438:1
    at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:416:1
    at Function.FiberUtils.synchronize (packages/peerlibrary_fiber-utils/packages/peerlibrary_fiber-utils.js:163:1)
    at Computation.Tracker.Computation.Computation._runInside (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:405:1)
    at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:430:1
    at Function.FiberUtils.synchronize (packages/peerlibrary_fiber-utils/packages/peerlibrary_fiber-utils.js:163:1)
    at Computation.Tracker.Computation.Computation._compute (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:427:1)
```

**Comment by mitar** [comment] 2016-01-20 16:26
I updated the title to reflect what we know about the issue.

**Comment by guilhermedecampo** [comment] 2016-01-20 17:24
@mitar I ended up using the raw observeChanges. Thanks!

**Comment by arist0tl3** [comment] 2016-02-03 09:52
Could be unrelated, but I threw this error earlier today...

```
error on fast-rendering path: /mobile/projectsList ; error: TypeError: Cannot call method 'idStringify' of undefined
    at PublishContext.publish.added (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:283:1)
    at packages/meteorhacks_fast-render/lib/server/publish_context.js:34:1
at Array.forEach (native)
at PublishContext._addCursor (packages/meteorhacks_fast-render/lib/server/publish_context.js:33:1)
at packages/meteorhacks_fast-render/lib/server/context.js:85:1
at Array.forEach (native)
at Context.processPublication (packages/meteorhacks_fast-render/lib/server/context.js:84:1)
at packages/meteorhacks_fast-render/lib/server/routes.js:122:1
at Array.forEach (native)
at Context.PublishContext.userId (packages/meteorhacks_fast-render/lib/server/routes.js:118:1)
```

Side note -- I had kadira running as well, but since dropping the fast-render package, haven't seen this error again.

**Comment by mitar** [comment] 2016-02-04 18:53
It seems there are two packages which are badly cooperating with this one:
- meteorhacks_fast-render
- meteorhacks_kadira

See those in stack-traces.

We should probably coordinate with @arunoda on a way to extend `publish` handle in a way which does not break other packages.

**Comment by SachaG** [comment] 2016-02-27 03:26
I'm having the same error using FlowRouter SSR:

```
error caught on publication:  { name: 'movies.list',
   params: [ { options: [Object], limit: 4 } ] } :  Cannot call method 
 Error when doing SSR. path:/: Cannot call method 'idStringify' of undefined
 TypeError: Cannot call method 'idStringify' of undefined
     at PublishContext.publish.added (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:283:1)
     at packages/meteorhacks_fast-render/lib/server/publish_context.js:34:1
     at Array.forEach (native)
     at PublishContext._addCursor (packages/meteorhacks_fast-render/lib/server/
     at packages/meteorhacks_fast-render/lib/server/context.js:85:1
     at Array.forEach (native)
     at Context.processPublication (packages/meteorhacks_fast-render/lib/server/
     at Context.subscribe (packages/meteorhacks_fast-render/lib/server/context.
     at SsrContext.addSubscription (packages/kadira:flow-router-ssr/server/
     at packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:9:18
```

**Comment by mitar** [comment] 2016-02-27 03:35
Is this happening occasionally or deterministicaly? Can somebody make small reproductions?

**Comment by SachaG** [comment] 2016-02-27 08:07
Here you go: 

https://github.com/SachaG/Reactive-Publish-Bug-Reproduction

Note that the bug seems to only be triggered when FlowRouter SSR tries to simulate a subscription to the publication server-side. So if you subscribe outside of your React component (on the client for example) it won't happen.

**Comment by mitar** [comment] 2016-02-27 08:08
Thanks! I was just about to try to do it myself, but I do not use any of those packages. I will look into this now.

**Comment by SachaG** [comment] 2016-02-27 08:10
Thanks! As far as I can tell, Reactive Publish is by far the best (and simplest) solution for reactive joins by the way. Great work :)

**Comment by mitar** [comment] 2016-02-27 08:12
> As far as I can tell, Reactive Publish is by far the best (and simplest) solution for reactive joins by the way.

I know. ;-) But it seems it is hard to get people to change their habits and their beliefs that there is no reactivity on the server side. :-)

**Comment by mitar** [comment] 2016-02-27 08:14
Hm, now we also need one reproduction for Kadira.

**Comment by SachaG** [comment] 2016-02-27 08:36
By the way [this](https://github.com/meteor-utilities/smart-publications) is what I'm using Reactive Publish for. It's a package that defines a convention to specify reactive joins in your schema.

**Comment by mitar** [comment] 2016-02-27 08:39
This looks a bit similar to [PeerDB](https://github.com/peerlibrary/meteor-peerdb). :-)

**Comment by mitar** [comment] 2016-02-27 12:43
OK, for SSR it seems that the issue is that SSR provides its own publish context to publish handlers which do not provide all the internal properties Meteor subscription context provide otherwise. See: https://github.com/kadirahq/fast-render/issues/159

I am not sure with Kadira. This issue is pretty linked only to SSR. Can somebody make a reproduction with Kadira?

**Comment by mitar** [comment] 2016-02-28 08:26
Using this branch seems to work: https://github.com/kadirahq/fast-render/pull/160

**Comment by mitar** [comment] 2016-02-28 09:54
I cannot reproduce it with kadira.

**Comment by mitar** [comment] 2016-03-01 18:11
You should use fast-render 2.13.0 to address this issue.

**Comment by mitar** [comment] 2016-03-14 03:08
Closing this as resolved. Please comment more if it is not.

**Closed as completed by mitar** 2016-03-14 03:08 UTC
Labels: help wanted, contributions welcome
