### ISSUE TITLE
why it doesn't work for me??help

### ISSUE THREAD

**Issue by violetbobo** [peerlibrary/meteor-reactive-publish#23] opened 2016-10-15 03:52 UTC
server publish:

```
Meteor.publish("loanTotal", function() {
    let user = Meteor.users.findOne({
        _id: this.userId
    });
    this.autorun(function () {
      console.log("enter in autorun!",user.username);
      //var result = loanLogs.aggregate(pipeline);
      var result = loanLogs.findOne({own:user.username,time:{$gt:new Date("2016-09-01")}});
      todayLoanTotal.remove({});
      todayLoanTotal.insert(result);
      return todayLoanTotal.find();
   });
});
```

client substrible:
`Meteor.subscribe('loanTotal');`

Now, when `loanLogs` changes, it doesn't trigger the autorun function, why? Do I miss something else?

**Comment by mitar** [comment] 2016-10-15 05:05
Hou you are doing aggregate? Is that reactive?

**Comment by fserg** [comment] 2016-11-20 16:35
The same problem!

**Comment by mitar** [comment] 2016-11-20 20:05
Again. What are you using for `aggregate`. That is not officially supported by Meteor. And even if it was, it has to be made reactive, what I think it is not.

**Comment by jaskinn** [comment] 2017-03-03 22:47
I assume that because the _aggregate_ line is commented out that it doesn't matter.

I'm curious how to test that _autorun_ is working. How do you test this sort of thing @mitar?

**Comment by jaskinn** [comment] 2017-03-03 22:51
And what happens if you do not pass _computation_ to the _autorun_ function?

**Comment by mitar** [comment] 2017-03-03 22:52
Please create a reproduction (a small repository with Meteor app which has only this problematic content and demonstrate that it does not work for you).

You can see tests I am using.

Also, `computation` is passed to your function which you pass to `autorun`, you do not have to pass it yourself.

**Comment by jaskinn** [comment] 2017-03-03 23:01
Regarding _computation_ - I mean what problems could occur if it (_computation_) is not passed to the _autorun_ function?

**Comment by mitar** [comment] 2017-03-03 23:08
Again, `computation` is passed to it by this package. You can ignore what is being passed. You do not have to specify it in your arguments your function accepts, JavaScript allows that, but computation is still passed to your function.

**Comment by jaskinn** [comment] 2017-03-03 23:09
Oh ok - great. Thanks.

**Comment by jaskinn** [comment] 2017-03-03 23:10
For me _reactive-publish_ is working exactly as expected. Sorry for the noise, I was just trying to help.

**Comment by mitar** [comment] 2017-03-03 23:13
I am closing this for now. If anyone wants to help with more information, please create a reproduction.

And yes, somebody could make aggregate pipelines into reactive queries. But that would also require that `observeChanges` and oplog would work on that. Which currently it does not yet. Probably a dirty solution would be to simply observe all documents matched by `$match` and then if anything changes, rerun the query. It could be expensive and slow though.

**Closed as completed by mitar** 2017-03-03 23:13 UTC
Labels: question, needs feedback
