### ISSUE TITLE
Error on Meteor Update 1.6.1 when using practicalmeteor:mocha

### ISSUE THREAD

**Issue by nonfungibletunji** [peerlibrary/meteor-reactive-publish#33] opened 2018-02-25 12:06 UTC
localCollectionLimit = new ReactiveVar(null);

Meteor 1.6.1 does not see the ReactiveVar inside the atmosphere package.
W20180225-07:01:23.344(-5)? (STDERR) ReferenceError: ReactiveVar is not defined
W20180225-07:01:23.344(-5)? (STDERR)     at _fn (packages/peerlibrary_reactive-publish.js:421:5)

**Comment by mitar** [comment] 2018-02-25 12:17
That's a bug in your app. This package is not using `ReactiveVar`.

**Comment by mitar** [comment] 2018-02-25 12:18
(It uses it only in tests. And dependency is defined [here](https://github.com/peerlibrary/meteor-reactive-publish/blob/master/package.js#L42).)

**Comment by nonfungibletunji** [comment] 2018-02-25 12:27
So Uses when running test on the package???

S Tunji Turner
sightuary
@sightuary

**Comment by mitar** [comment] 2018-02-25 12:28
But the dependency is defined in `package.js`.

**Comment by nonfungibletunji** [comment] 2018-02-25 12:33
Yeah but the package is setup for version 1.4+, I am running into the error using version meteor 1.6.1

S Tunji Turner
sightuary
@sightuary

**Comment by mitar** [comment] 2018-02-25 12:40
Just packages versions uses from 1.4

Anyway, I cannot reproduce your issue. I ran this on Meteor 1.6.1 and tests work for me.

**Comment by mitar** [comment] 2018-02-25 12:40
So please create a small reproduction.

**Comment by nonfungibletunji** [comment] 2018-02-25 12:42
Will do thanks 

S Tunji Turner
sightuary
@sightuary

**Comment by nonfungibletunji** [comment] 2018-02-25 15:01
I just removed the package, the app is a migration from 1.2 to 1.6.1.

S Tunji Turner
sightuary
@sightuary

**Comment by mitar** [comment] 2018-02-25 16:24
OK, but can you make a small app where this is failing like you are describing?

**Comment by nonfungibletunji** [comment] 2018-02-25 16:56
Yes I can

S Tunji Turner
sightuary
@sightuary

**Comment by atomoc** [comment] 2018-02-27 08:14
I have the same! 
![2018-02-27 11-13-30](https://user-images.githubusercontent.com/465108/36717499-59d4e71c-1baf-11e8-8b93-06f899076409.png)

**Comment by atomoc** [comment] 2018-02-27 08:29
And on command `meteor update --all-packages`:
```
This project is already at Meteor 1.6.1, the latest release.
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: Conflict: Constraint coffeescript@1.0.4 is not satisfied by coffeescript 2.2.1_1.
Constraints on package "coffeescript":
* coffeescript@1.0.4 <- zimme:collection-timestampable 1.0.9
* coffeescript@1.0.4 <- zimme:collection-behaviours 1.1.3 <- zimme:collection-timestampable 1.0.9
* coffeescript@2.0.3_3 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-mongo 0.2.2 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:fiber-utils 0.9.1 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-mongo 0.2.2 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:fiber-utils 0.9.1 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:reactive-mongo 0.2.2 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:extend-publish 0.5.0 <- peerlibrary:reactive-publish 0.6.0
```

**Comment by atomoc** [comment] 2018-02-27 08:31
And:
```
$ meteor add peerlibrary:reactive-publish@0.6.0
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint coffeescript@1.0.4 is not satisfied by coffeescript 2.0.3_4.
Constraints on package "coffeescript":
* coffeescript@1.0.4 <- zimme:collection-timestampable 1.0.9
* coffeescript@1.0.4 <- zimme:collection-behaviours 1.1.3 <- zimme:collection-timestampable 1.0.9
* coffeescript@2.0.3_3 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-mongo 0.2.2 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:fiber-utils 0.9.1 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-mongo 0.2.2 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:fiber-utils 0.9.1 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:reactive-mongo 0.2.2 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:extend-publish 0.5.0 <- peerlibrary:reactive-publish 0.6.0
```

**Comment by atomoc** [comment] 2018-02-27 08:32
It is necessary to refrain while from using.

**Comment by mitar** [comment] 2018-02-27 10:30
So nobody willing to create a reproduction?

**Comment by mitar** [comment] 2018-02-27 10:34
Because things work for me:

```
$ meteor create test-app
Created a new Meteor app in 'test-app'.       

To run your new app:                          
  cd test-app                                 
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials            
                                              
meteor create --bare to create an empty app.  
meteor create --full to create a scaffolded app.
                                              
$ cd test-app/
$ meteor add peerlibrary:reactive-publish
                                              
Changes to your project's package version selections:
                                              
coffeescript                  added, version 2.0.3_4
coffeescript-compiler         added, version 2.0.3_4
peerlibrary:assert            added, version 0.2.5
peerlibrary:extend-publish    added, version 0.5.0
peerlibrary:fiber-utils       added, version 0.9.1
peerlibrary:reactive-mongo    added, version 0.2.2
peerlibrary:reactive-publish  added, version 0.6.0
peerlibrary:server-autorun    added, version 0.7.1

                                              
peerlibrary:reactive-publish: Reactive publish endpoints
$ meteor           
[[[[[ .../test-app ]]]]]                   

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

**Comment by atomoc** [comment] 2018-02-27 10:38
Version of the meteor what?

**Comment by mitar** [comment] 2018-02-27 10:40
@atomoc, I do not understand your question.

**Comment by atomoc** [comment] 2018-02-27 10:46
Meteor v.1.6.1 ?

**Comment by mitar** [comment] 2018-02-27 10:47
Yes, this is what I just ran, which uses Meteor 1.6.1 by default. Please try to create a small reproduction yourself and put a repo on GitHub.

**Comment by atomoc** [comment] 2018-02-27 12:10
On a clean project with the same package.json and .meteor/packages files everything is ok, until I can understand what the problem is.

**Comment by nonfungibletunji** [comment] 2018-02-27 12:50
Again my test app deployed as well , with the dependency

S Tunji Turner
sightuary
@sightuary

**Comment by mitar** [comment] 2018-02-27 17:15
@stunjiturner, so does it work for you or no? I do not understand.

**Comment by nonfungibletunji** [comment] 2018-02-27 17:29
It does not work for the existing app, only for a newly created meteor 1.6.1 test app.

S Tunji Turner
sightuary
@sightuary

**Comment by mitar** [comment] 2018-02-27 17:31
OK. So please find what is the difference and make a reproduction. It works for me, so I cannot really help until we can at least have a small example.

**Comment by atomoc** [comment] 2018-02-27 17:32
I tried to use ReactiveVar yesterday, but I got errors. Clearly something is not so simple with him.

**Comment by atomoc** [comment] 2018-02-27 17:33
@mitar Here need a large reproduction most likely

**Comment by atomoc** [comment] 2018-02-27 17:35
I think the problem is in Cordova

**Comment by janat08** [comment] 2018-03-05 03:13
https://github.com/janat08/blockrazor/tree/reactivePublications
isn't small.

**Comment by brendonboshell** [comment] 2018-03-16 10:48
This issue seems to happen when other conflicting packages have been installed, perhaps due to the way Meteor resolves conflicting dependencies? For example, having both 'practicalmeteor:mocha' and 'peerlibrary:reactive-publish' packages will result in this error.

To replicate:

1. `meteor create simple-todos --release 1.6.1`
1. `cd simple-todos`
1. `meteor add practicalmeteor:mocha`
1. `meteor add peerlibrary:reactive-publish`
1. `meteor --inspect-brk`

![image](https://user-images.githubusercontent.com/951457/37516453-13d93132-2906-11e8-89de-dda5ce1afeb5.png)

It seems the `tests.coffee.js` file is included, which results in the `ReactiveVar is not defined` error.

Meteor decides to install `0.4.0`:

```
$ meteor list
autopublish                   1.0.7  (For prototyping only) Publish the entire database to all clients
blaze-html-templates          1.1.2  Compile HTML templates into reactive UI with Meteor Blaze
ecmascript                    0.10.5  Compiler plugin that supports ES2015+ in all .js files
es5-shim                      4.7.3  Shims and polyfills to improve ECMAScript 5 support
insecure                      1.0.7  (For prototyping only) Allow all database writes from the client
meteor-base                   1.3.0  Packages that every Meteor app needs
mobile-experience             1.0.5  Packages for a great mobile user experience
mongo                         1.4.5  Adaptor for using MongoDB and Minimongo over DDP
peerlibrary:reactive-publish  0.4.0* Reactive publish endpoints
practicalmeteor:mocha         2.4.5_6  Write package tests with mocha and run them in the browser or from the command line with spacejam.
reactive-var                  1.0.11  Reactive variable
shell-server                  0.3.1  Server-side component of the `meteor shell` command.
standard-minifier-css         1.4.1  Standard css minifier used with Meteor apps by default.
standard-minifier-js          2.3.2  Standard javascript minifiers used with Meteor apps by default.
tracker                       1.1.3  Dependency tracker to allow reactive callbacks
```

Running `meteor add peerlibrary:reactive-publish@0.6.0` results in:

```
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint coffeescript@1.0.4 is not satisfied by coffeescript 2.0.3_4.
Constraints on package "coffeescript":
* coffeescript@1.0.4 <- practicalmeteor:mocha 2.0.1-rc0
* coffeescript@2.0.3_3 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-mongo 0.2.2 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:fiber-utils 0.9.1 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-mongo 0.2.2 <-
peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:fiber-utils 0.9.1 <- peerlibrary:server-autorun 0.7.1 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:reactive-mongo 0.2.2 <- peerlibrary:reactive-publish 0.6.0
* coffeescript@2.0.3_3 <- peerlibrary:extend-publish 0.5.0 <- peerlibrary:reactive-publish 0.6.0

Conflict: Constraint spacejamio:chai@1.9.2_2 is not satisfied by spacejamio:chai 1.0.0.
Constraints on package "spacejamio:chai":
* spacejamio:chai@1.9.2_2 <- practicalmeteor:mocha 2.0.1-rc0
```

**Comment by knirirr** [comment] 2018-04-14 14:57
I'm seeing the same issue as @brendonboshell and can reproduce the same crash with the simple-todos as mentioned above. What I can't manage at the moment is to get node-inspector installed, apparently due to this issue:  https://github.com/node-inspector/v8-debug/issues/41

**Comment by opyh** [comment] 2018-04-17 21:19
I could solve the issue for me by running this command:

```bash
meteor update peerlibrary:reactive-publish  peerlibrary:server-autorun peerlibrary:fiber-utils  peerlibrary:reactive-mongo peerlibrary:extend-publish
```

**Comment by knirirr** [comment] 2018-05-05 13:39
If anyone has had any luck in finding a solution to this I'd be very interested to hear it.

Meanwhile, I note that an older version of my application using Meteor 1.6-beta.26 does not show this problem, so it does indeed seem to be related  to 1.6.1.

**Comment by mitar** [comment] 2018-05-05 14:42
I am using this package with 1.6.1.1 without any problems. I think the issue is in `practicalmeteor:mocha` which is forcing an old CoffeeScript version. It should be updated to CoffeeScript 2.

I am using [meteortesting:mocha](https://github.com/meteortesting/meteor-mocha) which works well.

**Comment by mitar** [comment] 2018-05-05 14:45
Not sure why it is not picking 0.5.0 though for you. That version of this package uses CoffeeScript 1 and works well.

**Comment by mitar** [comment] 2018-05-05 14:48
See issue here: https://github.com/practicalmeteor/meteor-mocha/issues/99

**Comment by mitar** [comment] 2018-05-05 14:49
And: https://github.com/practicalmeteor/meteor-mocha/pull/91

**Comment by mitar** [comment] 2018-05-05 14:50
So can somebody try `meteor add peerlibrary:reactive-publish@0.5.0` and report what happens?

**Comment by mitar** [comment] 2018-05-05 14:52
Ah, you get:

```
While selecting package versions:
error: Conflict: Constraint babel-compiler@6.13.0 is not satisfied by babel-compiler 7.0.8.
Constraints on package "babel-compiler":
* babel-compiler@~7.0.6 <- top level
* babel-compiler@7.0.0 <- ecmascript 0.10.8
* babel-compiler@7.0.0 <- minifier-js 2.3.4 <- standard-minifier-js 2.3.3
* babel-compiler@7.0.0 <- standard-minifier-js 2.3.3
* babel-compiler@6.13.0 <- coffeescript 1.11.1_3 <- peerlibrary:extend-publish 0.4.0 <- peerlibrary:reactive-publish 0.5.0
* babel-compiler@6.13.0 <- coffeescript 1.11.1_3 <- peerlibrary:reactive-publish 0.5.0
```

**Comment by mitar** [comment] 2018-05-05 14:54
So not sure how to fix this. It is really a problem of `practicalmeteor:mocha` for not being updated to 1.6.1.

**Comment by knirirr** [comment] 2018-05-05 16:39
Thanks for your further comments.
I've removed practicalmeteor:mocha and replaced it with meteortesting:mocha. Unfortunately, this issue persists. 

Edit: The list of packages I'm using is at https://bitbucket.org/knirirr/beecount3/src/4652c46442fee9443c69be0722c485babd19c0ba/.meteor/packages?at=master&fileviewer=file-view-default

**Comment by mitar** [comment] 2018-05-05 17:16
You have now update all packages with `meteor update --all-packages`.

**Comment by mitar** [comment] 2018-05-05 17:18
I still see `practicalmeteor:mocha` in your list of packages.

**Comment by knirirr** [comment] 2018-05-05 17:58
I've not checked in the changes I made locally, and don't plan to do so until I can get the application working again, so it still shows the old package.  In addition to the package removal/addition previously mentioned I've also run `meteor update --all-packages`, and the problem persists. This procedure should therefore reproduce the problem.

1. Clone https://bitbucket.org/knirirr/beecount3.git
2. meteor remove practicalmeteor:mocha
3. meteor add meteortesting:mocha
4. meteor update --all-packages
5. meteor

**Comment by mitar** [comment] 2018-05-06 04:40
Yea, you have other dependencies on old CoffeeScript. You should really complain to Meteor about all this situation. They managed to break many libraries using CoffeeScript and many of them are not maintained really anymore.

So try:

    1. Clone https://bitbucket.org/knirirr/beecount3.git
    2. meteor update
    3. meteor update --all-packages
    4. meteor add coffeescript@2.2.1_1

And you will see all conflicts.

```
* coffeescript@1.0.4 <- zimme:active-route 2.3.2
* coffeescript@1.0.4 <- softwarerero:accounts-t9n 1.3.11 <- useraccounts:core 1.14.2 <- useraccounts:flow-routing 1.14.2
* coffeescript@1.0.15 <- practicalmeteor:mocha 2.4.5_6
* coffeescript@1.0.3 <- practicalmeteor:loglevel 1.2.0_2 <- practicalmeteor:mocha 2.4.5_6
* coffeescript@1.0.3 <- practicalmeteor:chai 2.1.0_1 <- practicalmeteor:loglevel 1.2.0_2 <- practicalmeteor:mocha 2.4.5_6
* coffeescript@1.0.3 <- practicalmeteor:chai 2.1.0_1 <- practicalmeteor:mocha 2.4.5_6
* coffeescript@1.0.3 <- practicalmeteor:sinon 1.14.1_2
```

So besides `practicalmeteor:mocha` you have some other as well.

So there is not really much one can do here. Meteor broke that old already published packages do not work by forcing downgrade to broken versions. While new fixed packages require also other packages to be upgraded. And many are not maintained anymore.

**Comment by knirirr** [comment] 2018-05-06 10:05
Thanks for looking into it - I'll see about pursing the issue elsewhere in case I get any luck.
The testing packages I could probably dispense with (I need to re-work all my tests anyway) but the accounts stuff is essential.

**Comment by mitar** [comment] 2018-05-06 19:18
Accounts package moved to NPM: https://github.com/softwarerero/meteor-accounts-t9n#version-230

**Comment by mitar** [comment] 2018-09-09 06:03
I am using this in my own apps with Meteor 1.6.1 and `meteortesting:mocha` and I do not see any issues. So closing this now.

**Closed as completed by mitar** 2018-09-09 06:03 UTC
Labels: needs feedback
