### ISSUE TITLE
Is reactive-publish expected to work with this.changed on a "virtual" collection?

### ISSUE THREAD

**Issue by brucejo75** [peerlibrary/meteor-reactive-publish#36] opened 2018-06-17 14:50 UTC
### Environment
Meteor v1.7.0.3
reactive-publish 0.7.0

### Repro
I am using reactive-publish to join some data on my server and then publish a "virtual" collection.  That is... a collection that does not exist on the server.

I am using `this.added`, `this.changed` and `this.removed` to manage the collection.

Initially, I implemented with only `this.added` and `this.removed`.   All seemed to work fine, but in an effort to reduce the amount of data I send down the wire, I implemented `this.changed`.

All my calls and data on my end are working as expected, but a `this.removed` is being sent by reactive-publish that deletes my document.

Here is my DDP trace:
```
debug.js:12 receive {msg: "added", collection: "test", id: "sq3fyk6LZ63vBD3oX", fields: {…}}
debug.js:12 receive {msg: "changed", collection: "test", id: "sq3fyk6LZ63vBD3oX", fields: {…}}
debug.js:12 receive {msg: "removed", collection: "test", id: "sq3fyk6LZ63vBD3oX"}
```
the `this.removed` was sent by reactive-publish

**Result**: the document on the client is removed ☹️
**Expected**: reactive-publish to not send a removed and the document would be changed.

### Observations

reactive-publish is inserting a `this.removed` because it believes that there are no added documents at the code [here](https://github.com/peerlibrary/meteor-reactive-publish/blob/master/server.coffee#L114).  I think the reason it believes this is because of this [line](https://github.com/peerlibrary/meteor-reactive-publish/blob/master/server.coffee#L118).

(I am unclear on why the `documents` object would be reset)

**Comment by brucejo75** [comment] 2018-06-17 15:44
**Whoa**.  I just reverted back to using `this.added`.  It looks like reactive-publish is automatically determining the document changes and sending a `this.changed` instead of `this.added`? (I did not have my DDP trace on before)

Is this behavior documented somewhere?  And why does it do it?

Much simpler for me, but very unexpected behavior.

**Comment by brucejo75** [comment] 2018-06-18 17:32
I found another unexpected behavior.

If I determine that my document didn't change and I do not publish it, reactive-publish will remove it.

Essentially, working with reactive-publish I should only always use `this.added` for all of the documents.

reactive-publish will recognize when the document has not changed, has changed or has been deleted.

Very unexpected behavior.

**Comment by mitar** [comment] 2018-06-18 17:37
No, your publish function should behave like a regular publish function which runs only once. Do not try to optimize things by not publishing things. You would also not not publish things in a regular publish function. If you do not publish things there, it does not get published at rerun.

So, make your publish function inside `autorun` like you would be doing a publish function which runs only once. The rest is done by this package. If you want to make your local optimizations, then you do not need to use this package. You can then use regular server-side autorun with reactive mongo operations (two other packages this package depends on).

This package exists to make your existing publish functions automatically behave reactively. If you do things which take state of a previous publish call and influence the new call, this is not a regular publish function.

**Comment by mitar** [comment] 2018-06-18 17:41
And yes, this package does work with what you call virtual collections. You just have to implement it so that you simply do a join like you would always do an initial join. So how would you implement a publish function which does a join? Implement it like that. But then if an argument to publish function changes, the whole thing will be automatically rerun and only diff will be sent to the client.

**Comment by brucejo75** [comment] 2018-06-18 18:38
OK, I am trying to sort out how to think about this.  I think it is pretty different than a standard publish.  If I am right, I think it is worth some words on the README.

### For standard publish
1. Within a publish I can perform a `find` and return a cursor.  All good.  I am assuming that Meteor observes the cursor and then publishes all the `added`, `changed`, `removed` messages over DDP.
2. Within a publish I can perform a `find` and not return the cursor.  But then I could observe the cursor and within my callback I could send all my `added`, `changed`, `removed` for my values.  These functions will execute as called without Meteor intercepting them.

### reactive-publish
1. Within a reactive-publish I can perform a `find` and return a cursor.  All good.
Now instead of Meteor observing collection changes on publish. Reactive-publish does not observe the cursor, it intercepts the flow of `added` publish functions and then sorts them out to `added`, `changed`, `removed` calls.  To the caller the behavior is exactly the same as publish.1, but under the covers it is pretty different.
2. If I decide to publish my collection via `added`, `changed`, `removed` I should really only just call an `added` function because reactive-publish will intercept the `added` function to determine what `added, removed, changed` values to send over the wire.  This behavior is different than publish.2.

### Summary
Fundamentally, a standard publish and a reactive-publish differ by where they observe the changes in the pipeline:
- publish receives `<collection>.observe` callbacks and then sends `added`, `changed`, `removed` messages down the DDP pipe.
- reactive-publish observes the DDP `added` calls and then calculates the diffs to publish via the `added`, `changed`, `removed` calls.

The upshot is that I can simply fire the `added` functions and reactive-publish will do me the service of sorting out the right DDP calls to send.

**Comment by mitar** [comment] 2018-06-18 18:40
No, you should do exactly the same as for standard publish even for reactive-publish. See [tests for examples](https://github.com/peerlibrary/meteor-reactive-publish/blob/master/tests.coffee#L28).

**Comment by mitar** [comment] 2018-06-18 18:41
Really, make a regular publish work for you, and then just wrap it into an autorun.

**Comment by mitar** [comment] 2018-06-18 18:43
Of course it might be a bug somewhere, but I and many others are using this package in this way and it works for me. So I believe you are not really having a standard publish in your case but you are trying to optimize things thinking about reruns.

**Comment by brucejo75** [comment] 2018-06-18 21:36
Mitar, thanks very much for your responses and attention.

admittedly, I am confused 😕 , but fairly persistent 😺 

I tried your advice.  I created a working publish that relied on observing one of my collections and based on that I would call `this.changed`.  It worked great! 
Then I slapped it into a `this.autorun` and it still worked great!  😕 

But one of my reasons for using reactive-publish is so I can sidestep the use of `<cursor>.observeChanges`.  Which can get complicated if I want to watch 2 collections or maybe more...

Anyway, I published a [test](https://github.com/brucejo75/reactive-publish-test) that demonstrates the specific problem I am trying to understand.  Maybe you can see where my assumptions have erred?

Essentially, in the UI you can press the button and that will update a document in the TABLES collection.  On the publish I join one field of the TABLES collection into the FORMS collection to create the `test` collection.  Then I call `this.changed` on it.

You will see in the console of the UI that the `changed` packet is sent followed by a `removed` packet.

If you comment out this [line](https://github.com/brucejo75/reactive-publish-test/blob/master/server/main.js#L39), and only use `added`.  You will see that it works as expected.  But only an initial `added` message is actually sent followed by all `changed` messages.

Thanks!

**Comment by mitar** [comment] 2018-06-18 21:43
> If you comment out this line, and only use added. You will see that it works as expected. But only an initial added message is actually sent followed by all changed messages.

Yes, this is expected. Publish inside autorun should behave like a regular publish. So regular publish would just do join once, and do `added` with the result, no?

And autorun then does its magic and converts things to `changed` as necessary.

**Comment by mitar** [comment] 2018-06-18 21:44
BTW, this package is great for 1-1 (do two findOnes) and 1-many (one findOne + observe) joins, but not many-many. It will work, but it might not be the most efficient thing for many-many.

**Comment by brucejo75** [comment] 2018-06-18 23:13
Thanks for the feedback.  re: performance.

My primary pattern is that I look up a collection, this collection has ids that I need for the select on another collection.  I am assuming that may not be too bad?  Really only 2 reactive calls in the publish.

But, the select will change with the new data.

For my joins I could do a similiar thing:

1. Look up collection 1.
2. Look up collection 2.
3. use the data from both to create the joined data and don't call a find per collection join

thoughts?.

**Comment by mitar** [comment] 2018-06-18 23:51
The issue is that autorun reruns and republishes everything (and then diffs to send only diffs to the client, but diffing still costs CPU) at any change in any collection. So if you are doing many-many join this will happen often.

For the thing you are doing, I am using now a bit old [peerdb](https://github.com/peerlibrary/meteor-peerdb). And I just embed data from second collection into the first.

**Comment by mitar** [comment] 2018-09-09 06:04
Closing this as answered.

**Closed as completed by mitar** 2018-09-09 06:04 UTC
Labels: question
